### ISSUE TITLE
Adjust site content and support switch networks

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/aragonette#13]
- [x] There should be no space between 'Ring' and 'DAO'; it needs to be changed to 'RingDAO'.
<img width="190" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/2ac13b24-413b-49c2-ada8-1eda3e86e6c2">

- [x] Delete this logo and change the content when the user selects a different chain.
<img width="513" alt="image" src="https://github.com/user-attachments/assets/ce81eea0-8cfb-4a89-84bc-56c9d1c8b420">

- When choosing Darwinia: RingDAO
- When choosing Crab: CrabDAO (no logo needed, text only)
- When choosing Koi: RingDAO Test Version

**Comment by nblogist** [comment]
@hamidroohi71 @hamidroohi92

**Comment by hamidroohi92** [comment]
This is done just for the first part of the issue. The second one should be fixed after adding other networks

**Comment by boundless-forest** [comment]
Any updates?

**Comment by hamidroohi92** [comment]
I am working on the chain support. Let me give you the result of it first, and then fix the logo according to its result.

**Comment by hamidroohi92** [comment]
> Any updates?

I added darwinia to the repo but can and koi not yet

**Comment by hamidroohi92** [comment]
All the needed networks have been added. The draft pull request is created.

**Comment by hackfisher** [comment]
Switch chain fixed by #22 

But Adjust site content still need fix.

**Comment by hamidroohi92** [comment]
This is fixed now By #24
