### ISSUE TITLE
Remove extra no-use url deployment and use wallet to switch different networks 

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/aragonette#14]
Koi: [koi-vote.ringdao.com](http://koi-vote.ringdao.com/)
Crab: [crab-vote.ringdao.com](http://crab-vote.ringdao.com/)

Add Crab and Darwinia Network support here after contract deployment.

![image (9)](https://github.com/user-attachments/assets/78d093a3-2e55-4336-98fc-5b595b718362)

**Comment by hackfisher** [comment]
Just confirm with @hujw77 , due to the framework limitation, we can not config multiple networks in the same env files, so this issue need to be reverted and keep:

Koi: [koi-vote.ringdao.com](http://koi-vote.ringdao.com/)
Crab: [crab-vote.ringdao.com](http://crab-vote.ringdao.com/)

**Comment by hamidroohi92** [comment]
> Just confirm with @hujw77 , due to the framework limitation, we can not config multiple networks in the same env files, so this issue need to be reverted and keep:
> 
> Koi: [koi-vote.ringdao.com](http://koi-vote.ringdao.com/) Crab: [crab-vote.ringdao.com](http://crab-vote.ringdao.com/)

If you mean the front end code, I can add chain supports to it.

**Comment by nblogist** [comment]
@fewensa did we mean to close it earlier? @hamidroohi92 @hamidroohi71 have added the networks in #20
