### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/aragonette#4]
1. Remove dashboard.
2. Change to RingDAO's logo and title.
3. Update style to RingDAO style.
4. Clean walletconnet.
5. Clean and update footer.
6. Reference: 
- https://staging-taiko-dao-ui.vercel.app/plugins/community-proposals/#/
- https://github.com/aragon/taiko-ui
7. Url:
- Koi: koi-vote.ringdao.com
- Crab: crab-vote.ringdao.com
- Darwinia: vote.ringdao.com

**Comment by hackfisher** [comment]
@nblogist we are going to handle this after paralink ui task

**Comment by 1022ranji** [comment]
> Remove dashboard.
> Change to RingDAO's logo and title.

@nblogist @hamidroohi71 Could you please first handle the dashboard and logo sections that Echo mentioned above? This will make it easier for Yalin to proceed with the deployment of vote.ringdao.com. And, please also add the following message at the top of the page so that there is no misunderstanding on the part of the user: "This is a BETA version. Features and performance may be subject to change and may contain bugs."

**Comment by hamidroohi71** [comment]
Ok. I am on them and let you know when they are fixed tomorrow

**Comment by hamidroohi71** [comment]
I put the things here to show you the progress:

- [x] Remove dashboard. 
- [x] Change to RingDAO's logo and title.
- [ ] Update style to RingDAO style.
- [x] Clean walletconnet.
- [x] Clean and update footer.

**Comment by 1022ranji** [comment]
@nblogist Could you please add the following disclaimer at the top of the page to avoid any potential misunderstandings from users in this pull request https://github.com/ringecosystem/vote.ringdao.com/pull/12:

"This is a BETA version. Features and performance are subject to change and may contain bugs."

Additionally, @fewensa could you assist with the development for the following URLs:

> 
> Koi: koi-vote.ringdao.com
> Crab: crab-vote.ringdao.com
> Darwinia: vote.ringdao.com

**Comment by nblogist** [comment]
@hamidroohi71 @hamidroohi92

**Comment by hamidroohi92** [comment]
> @nblogist Could you please add the following disclaimer at the top of the page to avoid any potential misunderstandings from users in this pull request #12:
> 
> "This is a BETA version. Features and performance are subject to change and may contain bugs."
> 
> Additionally, @fewensa could you assist with the development for the following URLs:
> 
> > Koi: koi-vote.ringdao.com
> > Crab: crab-vote.ringdao.com
> > Darwinia: vote.ringdao.com

This is Done and added
